/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.kimjeeyoung.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TypeC extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1950672527091394226L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TypeC\",\"namespace\":\"com.kimjeeyoung.avro\",\"fields\":[{\"name\":\"another_value\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int another_value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public TypeC() {}

  /**
   * All-args constructor.
   */
  public TypeC(java.lang.Integer another_value) {
    this.another_value = another_value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return another_value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: another_value = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'another_value' field.
   */
  public java.lang.Integer getAnotherValue() {
    return another_value;
  }

  /**
   * Sets the value of the 'another_value' field.
   * @param value the value to set.
   */
  public void setAnotherValue(java.lang.Integer value) {
    this.another_value = value;
  }

  /**
   * Creates a new TypeC RecordBuilder.
   * @return A new TypeC RecordBuilder
   */
  public static com.kimjeeyoung.avro.TypeC.Builder newBuilder() {
    return new com.kimjeeyoung.avro.TypeC.Builder();
  }
  
  /**
   * Creates a new TypeC RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TypeC RecordBuilder
   */
  public static com.kimjeeyoung.avro.TypeC.Builder newBuilder(com.kimjeeyoung.avro.TypeC.Builder other) {
    return new com.kimjeeyoung.avro.TypeC.Builder(other);
  }
  
  /**
   * Creates a new TypeC RecordBuilder by copying an existing TypeC instance.
   * @param other The existing instance to copy.
   * @return A new TypeC RecordBuilder
   */
  public static com.kimjeeyoung.avro.TypeC.Builder newBuilder(com.kimjeeyoung.avro.TypeC other) {
    return new com.kimjeeyoung.avro.TypeC.Builder(other);
  }
  
  /**
   * RecordBuilder for TypeC instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TypeC>
    implements org.apache.avro.data.RecordBuilder<TypeC> {

    private int another_value;

    /** Creates a new Builder */
    private Builder() {
      super(com.kimjeeyoung.avro.TypeC.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kimjeeyoung.avro.TypeC.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.another_value)) {
        this.another_value = data().deepCopy(fields()[0].schema(), other.another_value);
        fieldSetFlags()[0] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing TypeC instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kimjeeyoung.avro.TypeC other) {
            super(com.kimjeeyoung.avro.TypeC.SCHEMA$);
      if (isValidValue(fields()[0], other.another_value)) {
        this.another_value = data().deepCopy(fields()[0].schema(), other.another_value);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'another_value' field.
      * @return The value.
      */
    public java.lang.Integer getAnotherValue() {
      return another_value;
    }

    /**
      * Sets the value of the 'another_value' field.
      * @param value The value of 'another_value'.
      * @return This builder.
      */
    public com.kimjeeyoung.avro.TypeC.Builder setAnotherValue(int value) {
      validate(fields()[0], value);
      this.another_value = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'another_value' field has been set.
      * @return True if the 'another_value' field has been set, false otherwise.
      */
    public boolean hasAnotherValue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'another_value' field.
      * @return This builder.
      */
    public com.kimjeeyoung.avro.TypeC.Builder clearAnotherValue() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public TypeC build() {
      try {
        TypeC record = new TypeC();
        record.another_value = fieldSetFlags()[0] ? this.another_value : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
