/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.kimjeeyoung.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TypeB extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4087197586021284093L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TypeB\",\"namespace\":\"com.kimjeeyoung.avro\",\"fields\":[{\"name\":\"value\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public TypeB() {}

  /**
   * All-args constructor.
   */
  public TypeB(java.lang.CharSequence value) {
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Creates a new TypeB RecordBuilder.
   * @return A new TypeB RecordBuilder
   */
  public static com.kimjeeyoung.avro.TypeB.Builder newBuilder() {
    return new com.kimjeeyoung.avro.TypeB.Builder();
  }
  
  /**
   * Creates a new TypeB RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TypeB RecordBuilder
   */
  public static com.kimjeeyoung.avro.TypeB.Builder newBuilder(com.kimjeeyoung.avro.TypeB.Builder other) {
    return new com.kimjeeyoung.avro.TypeB.Builder(other);
  }
  
  /**
   * Creates a new TypeB RecordBuilder by copying an existing TypeB instance.
   * @param other The existing instance to copy.
   * @return A new TypeB RecordBuilder
   */
  public static com.kimjeeyoung.avro.TypeB.Builder newBuilder(com.kimjeeyoung.avro.TypeB other) {
    return new com.kimjeeyoung.avro.TypeB.Builder(other);
  }
  
  /**
   * RecordBuilder for TypeB instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TypeB>
    implements org.apache.avro.data.RecordBuilder<TypeB> {

    private java.lang.CharSequence value;

    /** Creates a new Builder */
    private Builder() {
      super(com.kimjeeyoung.avro.TypeB.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kimjeeyoung.avro.TypeB.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing TypeB instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kimjeeyoung.avro.TypeB other) {
            super(com.kimjeeyoung.avro.TypeB.SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.CharSequence getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.kimjeeyoung.avro.TypeB.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.kimjeeyoung.avro.TypeB.Builder clearValue() {
      value = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public TypeB build() {
      try {
        TypeB record = new TypeB();
        record.value = fieldSetFlags()[0] ? this.value : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
