/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.kimjeeyoung.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TypeAWithNewField extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8535104143218580171L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TypeAWithNewField\",\"namespace\":\"com.kimjeeyoung.avro\",\"fields\":[{\"name\":\"value\",\"type\":\"string\"},{\"name\":\"new_value\",\"type\":\"string\",\"default\":\"default-value\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence value;
  @Deprecated public java.lang.CharSequence new_value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public TypeAWithNewField() {}

  /**
   * All-args constructor.
   */
  public TypeAWithNewField(java.lang.CharSequence value, java.lang.CharSequence new_value) {
    this.value = value;
    this.new_value = new_value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    case 1: return new_value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.lang.CharSequence)value$; break;
    case 1: new_value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'new_value' field.
   */
  public java.lang.CharSequence getNewValue() {
    return new_value;
  }

  /**
   * Sets the value of the 'new_value' field.
   * @param value the value to set.
   */
  public void setNewValue(java.lang.CharSequence value) {
    this.new_value = value;
  }

  /**
   * Creates a new TypeAWithNewField RecordBuilder.
   * @return A new TypeAWithNewField RecordBuilder
   */
  public static com.kimjeeyoung.avro.TypeAWithNewField.Builder newBuilder() {
    return new com.kimjeeyoung.avro.TypeAWithNewField.Builder();
  }
  
  /**
   * Creates a new TypeAWithNewField RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TypeAWithNewField RecordBuilder
   */
  public static com.kimjeeyoung.avro.TypeAWithNewField.Builder newBuilder(com.kimjeeyoung.avro.TypeAWithNewField.Builder other) {
    return new com.kimjeeyoung.avro.TypeAWithNewField.Builder(other);
  }
  
  /**
   * Creates a new TypeAWithNewField RecordBuilder by copying an existing TypeAWithNewField instance.
   * @param other The existing instance to copy.
   * @return A new TypeAWithNewField RecordBuilder
   */
  public static com.kimjeeyoung.avro.TypeAWithNewField.Builder newBuilder(com.kimjeeyoung.avro.TypeAWithNewField other) {
    return new com.kimjeeyoung.avro.TypeAWithNewField.Builder(other);
  }
  
  /**
   * RecordBuilder for TypeAWithNewField instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TypeAWithNewField>
    implements org.apache.avro.data.RecordBuilder<TypeAWithNewField> {

    private java.lang.CharSequence value;
    private java.lang.CharSequence new_value;

    /** Creates a new Builder */
    private Builder() {
      super(com.kimjeeyoung.avro.TypeAWithNewField.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kimjeeyoung.avro.TypeAWithNewField.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.new_value)) {
        this.new_value = data().deepCopy(fields()[1].schema(), other.new_value);
        fieldSetFlags()[1] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing TypeAWithNewField instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kimjeeyoung.avro.TypeAWithNewField other) {
            super(com.kimjeeyoung.avro.TypeAWithNewField.SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.new_value)) {
        this.new_value = data().deepCopy(fields()[1].schema(), other.new_value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.CharSequence getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.kimjeeyoung.avro.TypeAWithNewField.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.kimjeeyoung.avro.TypeAWithNewField.Builder clearValue() {
      value = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_value' field.
      * @return The value.
      */
    public java.lang.CharSequence getNewValue() {
      return new_value;
    }

    /**
      * Sets the value of the 'new_value' field.
      * @param value The value of 'new_value'.
      * @return This builder.
      */
    public com.kimjeeyoung.avro.TypeAWithNewField.Builder setNewValue(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.new_value = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'new_value' field has been set.
      * @return True if the 'new_value' field has been set, false otherwise.
      */
    public boolean hasNewValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'new_value' field.
      * @return This builder.
      */
    public com.kimjeeyoung.avro.TypeAWithNewField.Builder clearNewValue() {
      new_value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public TypeAWithNewField build() {
      try {
        TypeAWithNewField record = new TypeAWithNewField();
        record.value = fieldSetFlags()[0] ? this.value : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.new_value = fieldSetFlags()[1] ? this.new_value : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
